deploy:

    needs: verify-and-package

    runs-on: ubuntu-latest

    permissions:

      contents: 'read'

      id-token: 'write'


    steps:

    - uses: actions/checkout@v3

    - id: 'auth'

      uses: 'google-github-actions/auth@v1'

      with:

        credentials_json: '${{ secrets.GCLOUD_SA }}'


    - id: 'get-credentials'

      uses: 'google-github-actions/get-gke-credentials@v1'

      with:

        cluster_name: 'apsv-24'

        location: 'us-central1'


    # The KUBECONFIG env var is automatically exported and picked up by kubectl.

    - id: 'deployment-mypod'

      run: 'kubectl create secret docker-registry github-registry --docker-server="ghcr.io" --docker-username="jimmyto-09" --docker-password="${{ secrets.PAT }}" --docker-email="jimmy.acastilloa@gmail.com" -o yaml --dry-run=client | kubectl apply -f -'

    - run: 'kubectl apply -f deployment.yaml'

    - run: 'kubectl get deployments'

    - run: 'kubectl get pods'